# Generated by Django 4.2 on 2023-04-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_payment_price_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price_payment',
        ),
    ]
