# Generated by Django 4.2 on 2023-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_payment_amount_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_address',
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_term',
            field=models.IntegerField(default=1),
        ),
    ]
